<a href="https://colab.research.google.com/github/safia211/Numpy_Assignment_PIAIC114755/blob/main/Assignment_2(Numpy_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
import numpy as np
array=np.arange(10).reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [ ]:
array1=np.arange(10).reshape(2,5)
array2=np.ones((2,5) ,dtype=int)
array3=np.concatenate((array1,array2), axis=0)
array3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [ ]:
array1=np.arange(10).reshape(2,5)
array2=np.ones((2,5) ,dtype=int)
array3=np.concatenate((array1,array2), axis=1)
array3

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [ ]:
y = np.arange(10).reshape(2,5)
x=y.flatten()
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [ ]:
y = np.arange(15).reshape(5,3)
print("array of higher dimension",y)
x=y.flatten()
print(" converted array a from higher to one dimension",x)

array of higher dimension [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
 converted array a from higher to one dimension [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [ ]:
y = np.arange(15)
print("array of one dimension",y)
x=y.reshape(5,3)
print("\n converted array a from one dimension to higher dimension \n",x)

array of one dimension [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

 converted array a from one dimension to higher dimension 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

## Question:8

### Create 5x6 an array and find the mean?

In [ ]:
arr=np.random.rand(5,5)
sq_arr=np.sqrt(arr)
sq_arr

array([[0.76759013, 0.71893673, 0.79293036, 0.75915655, 0.49399025],
       [0.75350939, 0.95948708, 0.72809255, 0.29174302, 0.61098989],
       [0.61720325, 0.33516107, 0.45275462, 0.56617205, 0.87860177],
       [0.40765018, 0.88124739, 0.41511568, 0.45541223, 0.74394407],
       [0.80964032, 0.46099162, 0.45360045, 0.74723691, 0.29887343]])

## Question:9

### Find the standard deviation of the previous array in Q8?

In [ ]:
arr_std=np.std(arr)
arr_std

0.23669876347603513

## Question:10

### Find the median of the previous array in Q8?

In [ ]:
arr_med=np.median(arr)
arr_med

0.38093984722693464

## Question:11

### Find the transpose of the previous array in Q8?

In [ ]:
arr_trans=np.transpose(arr)
arr_trans

array([[0.58919461, 0.5677764 , 0.38093985, 0.16617867, 0.65551744],
       [0.51687002, 0.92061546, 0.11233294, 0.77659696, 0.21251327],
       [0.62873855, 0.53011876, 0.20498675, 0.17232103, 0.20575336],
       [0.57631867, 0.08511399, 0.3205508 , 0.2074003 , 0.558363  ],
       [0.24402637, 0.37330865, 0.77194106, 0.55345278, 0.08932532]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [ ]:
array=np.random.rand(4,4)
arr_trace=np.trace(array)
arr_trace

1.6546148261079

## Question:13

### Find the determinant of the previous array in Q12?

In [ ]:
arr_det=np.linalg.det(array)
arr_det

0.15183593367373452

## Question:14

### Find the 5th and 95th percentile of an array?

In [ ]:
array=np.random.rand(20)
arr=print("5th percentile of an array is ", np.percentile(array,50),  "\n 95th percentile of an array is "
         ,np.percentile(array,95))

## Question:15

### How to find if a given array has any null values?

In [ ]:
array=np.random.rand(12)
array
y=np.where(np.isnan(array),"null value","not a null value")
y

array(['not a null value', 'not a null value', 'not a null value',
       'not a null value', 'not a null value', 'not a null value',
       'not a null value', 'not a null value', 'not a null value',
       'not a null value', 'not a null value', 'not a null value'],
      dtype='<U16')